name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/GihanSoft/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create the package 1
      run: dotnet pack -c Release src/GihanSoft.Security.Cryptography.Abstractions --no-restore
    - name: Create the package 2
      run: dotnet pack -c Release src/GihanSoft.Security.Cryptography.Aes --no-restore
    - name: Publish the package to GPR 1
      run: dotnet nuget push src/GihanSoft.Security.Cryptography.Abstractions/bin/Release/*.nupkg --skip-duplicate
    - name: Publish the package to GPR 2
      run: dotnet nuget push src/GihanSoft.Security.Cryptography.Aes/bin/Release/*.nupkg --skip-duplicate
    - name: Publish the package to nuget.org 1
      run: dotnet nuget push src/GihanSoft.Security.Cryptography.Abstractions/bin/Release/*.nupkg -k oy2bimpr7ampbsxkwlaqtsilklomemledosh5y3c545ok4 -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish the package to nuget.org 2
      run: dotnet nuget push src/GihanSoft.Security.Cryptography.Aes/bin/Release/*.nupkg -k oy2bimpr7ampbsxkwlaqtsilklomemledosh5y3c545ok4 -s https://api.nuget.org/v3/index.json --skip-duplicate
