name: publish Pbkdf2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/GihanSoft.Security.Cryptography.Pbkdf2/GihanSoft.Security.Cryptography.Pbkdf2.csproj
        NUGET_KEY: ${{ secrets.NUGET_KEY }}

