name: publish AES

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Install dependencies
      run: dotnet restore
    - name: Create the package
      run: dotnet pack -c Release src/GihanSoft.Security.Cryptography.Aes --no-restore
    - name: Publish the package to nuget.org 1
      run: dotnet nuget push src/GihanSoft.Security.Cryptography.Aes/bin/Release/*.nupkg --skip-duplicate
    
